### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by IS4Code** [njsmith/redll#2]
Please upload a fully working release that does work without having to find and install any Python. It's been a pain to get this running without any knowledge of Python.

**Comment by njsmith** [comment]
Sorry to hear you struggled, but this is a random little project to scratch my own itch, and it works fine for me. If you have some question or want to help out that's cool, but this sort of comes across like me calling you up and demanding that you come over and walk my dog for me. Bit rude, don't you think?
